name: Build and Push Docker image to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Clone code to runner
      - name: Checkout
        uses: actions/checkout@v4

      # Push the image to GHCR (Image Registry)
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
